[package]
name = "lsedit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
clap = { version = "*", features = ["derive"] }
comfy-table = "*"
tar = "*"
flate2 = "*"
futures-util = "*"
sha256 = "*"
lslib = { path = "../lslib" }
quick-xml = { version = "*", features = ["serialize"] }
dirs-next = "*"
tui = "*"
crossterm = "*"
